blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabilities
    url: https://github.com/palekiwi-labs/ocx/blob/master/SECURITY.md
    about: Please report security vulnerabilities privately.
